# <u> Use only those concepts which have been taught till now </u>

In [28]:
import numpy as np

# <u>**Problem 1**</u>

### What is the average value of the first 5 rows of the third and fourth columns?



In [29]:
np.random.seed(21) # This guarantees the code will generate the same set of random numbers whenever executed
random_integers = np.random.randint(1,high=500000, size=(20, 5))
random_integers

array([[ 80842, 333008, 202553, 140037,  81969],
       [ 63857,  42105, 261540, 481981, 176739],
       [489984, 326386, 110795, 394863,  25024],
       [ 38317,  49982, 408830, 485118,  16119],
       [407675, 231729, 265455, 109413, 103399],
       [174677, 343356, 301717, 224120, 401101],
       [140473, 254634, 112262,  25063, 108262],
       [375059, 406983, 208947, 115641, 296685],
       [444899, 129585, 171318, 313094, 425041],
       [188411, 335140, 141681,  59641, 211420],
       [287650,   8973, 477425, 382803, 465168],
       [  3975,  32213, 160603, 275485, 388234],
       [246225,  56174, 244097,   9350, 496966],
       [225516, 273338,  73335, 283013, 212813],
       [ 38175, 282399, 318413, 337639, 379802],
       [198049, 101115, 419547, 260219, 325793],
       [148593, 425024, 348570, 117968, 107007],
       [ 52547, 180346, 178760, 305186, 262153],
       [ 11835, 449971, 494184, 472031, 353049],
       [476442,  35455, 191553, 384154,  29917]])

In [30]:
# Your code here
avg = np.mean(random_integers[0:5, 2:4])
round(avg, ndigits=2)
print(avg)

286058.5


#<u>**Problem 2**</u>

### In this problem, we are going to calculate distances between some pairs of points :

### <u> Measures of distances </u>
* ### Euclidean Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)={\sqrt {(x_{1}-x_{2})^{2}+(y_{1}-y_{2})^{2}}}.}$

* ### Manhattan Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)=|x_{1}-x_{2}|+|y_{1}-y_{2}|}$


### Create a 2-D array of 10 points where the x-coordinates and the y-coordinates can take random integral values between 5 and 20.


### Next, create two 1-D arrays(one for  Euclidean distance and the other for  Manhattan distance) for these points


In [31]:
# Create the 10 points
import numpy as np

# Generate 10 random points (x, y) with coordinates between 5 and 20
np.random.seed(42)  # For reproducibility
points = np.random.randint(low=5, high=21, size=(10, 2))

In [32]:
# Calculate Euclidean distances between these pairs of points (total 10*10 = 100 pairs including self pairs). This should give you a 10*10 2-D array where each value corresponds to the distance between a pair
euclidean_distances = np.zeros((10, 10))
for i in range(10):
    for j in range(10):
        euclidean_distances[i, j] = np.linalg.norm(points[i] - points[j])

In [33]:
# Calculate Manhattan distances between these pairs of points (total 10*10 = 100 pairs inlcuding self pairs).This should give you a 10*10 2-D array where each value corresponds to the distance between a pair.
manhattan_distances = np.zeros((10, 10))
for i in range(10):
    for j in range(10):
        manhattan_distances[i, j] = np.sum(np.abs(points[i] - points[j]))

## Find the closest pairs (excluding self pairs) on the basis of both the distance measures

In [34]:
# Your code here
# Exclude self-pairs (diagonal elements)
np.fill_diagonal(euclidean_distances, np.inf)
np.fill_diagonal(manhattan_distances, np.inf)

# Find closest pairs based on both distance measures
closest_euclidean_pair = np.unravel_index(np.argmin(euclidean_distances), euclidean_distances.shape)
closest_manhattan_pair = np.unravel_index(np.argmin(manhattan_distances), manhattan_distances.shape)

print("Random Points (x, y):")
print(points)
print("\nEuclidean Distances:")
print(euclidean_distances)
print("\nManhattan Distances:")
print(manhattan_distances)
print("\nClosest Euclidean Pair:", closest_euclidean_pair)
print("Closest Manhattan Pair:", closest_manhattan_pair)




Random Points (x, y):
[[11  8]
 [17 19]
 [15 12]
 [17  9]
 [11 14]
 [ 7 11]
 [15 15]
 [12  9]
 [ 8 12]
 [12  7]]

Euclidean Distances:
[[        inf 12.52996409  5.65685425  6.08276253  6.          5.
   8.06225775  1.41421356  5.          1.41421356]
 [12.52996409         inf  7.28010989 10.          7.81024968 12.80624847
   4.47213595 11.18033989 11.40175425 13.        ]
 [ 5.65685425  7.28010989         inf  3.60555128  4.47213595  8.06225775
   3.          4.24264069  7.          5.83095189]
 [ 6.08276253 10.          3.60555128         inf  7.81024968 10.19803903
   6.32455532  5.          9.48683298  5.38516481]
 [ 6.          7.81024968  4.47213595  7.81024968         inf  5.
   4.12310563  5.09901951  3.60555128  7.07106781]
 [ 5.         12.80624847  8.06225775 10.19803903  5.                 inf
   8.94427191  5.38516481  1.41421356  6.40312424]
 [ 8.06225775  4.47213595  3.          6.32455532  4.12310563  8.94427191
          inf  6.70820393  7.61577311  8.54400375]
 [ 1.4

# <u>**Problem 3**</u>

## Extract all the contiguous 3x3 blocks from a random 10x10 matrix. For example, the first matrix corresponds to [:3,:3], then the second matrix corresponds to [:3,1:4],.... Once you have covered the first three rows, then the next set of matrices would be [1:4,:3],[1:4,1:4],.... and so on and so forth. The last matrix would be [7:10,7:10]

In [35]:
# Your code below ..
import numpy as np
random_matrix = np.random.randint(1, 100, size=(10, 10))
# Initialize an empty list to store the 3x3 blocks
blocks = []
# Iterate through rows and columns
for i in range(8):  # Rows: 0 to 7
    for j in range(8):  # Columns: 0 to 7
        # Extract the 3x3 block
        block = random_matrix[i:i+3, j:j+3]
        blocks.append(block)

# Print the extracted blocks
for idx, block in enumerate(blocks):
    print(f"Block {idx+1}:\n{block}\n")

# Example: Access the first block ([:3, :3])
print("Example - First block:")
print(blocks[0])

Block 1:
[[22 53  2]
 [33 76 58]
 [60 80 15]]

Block 2:
[[53  2 88]
 [76 58 22]
 [80 15 62]]

Block 3:
[[ 2 88 30]
 [58 22 89]
 [15 62 62]]

Block 4:
[[88 30 38]
 [22 89 49]
 [62 62 47]]

Block 5:
[[30 38  2]
 [89 49 91]
 [62 47 62]]

Block 6:
[[38  2 64]
 [49 91 59]
 [47 62 51]]

Block 7:
[[ 2 64 60]
 [91 59 42]
 [62 51 55]]

Block 8:
[[64 60 21]
 [59 42 92]
 [51 55 64]]

Block 9:
[[33 76 58]
 [60 80 15]
 [ 3 51  7]]

Block 10:
[[76 58 22]
 [80 15 62]
 [51  7 21]]

Block 11:
[[58 22 89]
 [15 62 62]
 [ 7 21 73]]

Block 12:
[[22 89 49]
 [62 62 47]
 [21 73 39]]

Block 13:
[[89 49 91]
 [62 47 62]
 [73 39 18]]

Block 14:
[[49 91 59]
 [47 62 51]
 [39 18  4]]

Block 15:
[[91 59 42]
 [62 51 55]
 [18  4 89]]

Block 16:
[[59 42 92]
 [51 55 64]
 [ 4 89 60]]

Block 17:
[[60 80 15]
 [ 3 51  7]
 [14  9 90]]

Block 18:
[[80 15 62]
 [51  7 21]
 [ 9 90 53]]

Block 19:
[[15 62 62]
 [ 7 21 73]
 [90 53  2]]

Block 20:
[[62 62 47]
 [21 73 39]
 [53  2 84]]

Block 21:
[[62 47 62]
 [73 39 18]
 [ 2 84 92]]

B

#<u>**Problem 4**</u>

### Write a function which finds the nearest value from a given value in an array of random N elements. Suppose you created an 1-D array with 15 elements taking values between 10 and 500. Your function would take any input from these values and return the nearest value. (You can use np.abs() function)

In [36]:
# Your function below
import numpy as np

def find_nearest(array, value):
    """
    Finds the nearest value in the given array to the specified value.

    Args:
        array (numpy.ndarray): 1-D array of random N elements.
        value (float): Input value for which we want to find the nearest value.

    Returns:
        float: Nearest value in the array.
    """
    array = np.asarray(array)
    idx = (np.abs(array - value)).argmin()
    return array[idx]

# Example usage:
random_array = np.random.randint(10, 501, size=15)  # Create a random 1-D array
input_value = 250  # Example input value
nearest_value = find_nearest(random_array, input_value)
print(f"Nearest value to {input_value} in the array: {nearest_value:.2f}")

Nearest value to 250 in the array: 240.00
